<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 7db012ca-d75c-49b7-8093-84477c566bb5
 * Migration local datetime: 2023-12-10 11:33:13.392604
 * Migration UTC datetime: 2023-12-10 05:33:13.392604
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2023121011331339 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('shirt_sizes', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->string('name', 255)->nullable(true);
        });
        Schema::create('people', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->uuid('employee_id')->nullable(true);
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->string('status')->nullable(true);
            $table->string('first_name')->nullable(true);
            $table->string('middle_name')->nullable(true);
            $table->string('last_name')->nullable(true);
            $table->string('preferred_name')->nullable(true);
            $table->dateTime('date_of_birth')->nullable(true);
            $table->string('gender')->nullable(true);
            $table->string('marital_status')->nullable(true);
            $table->string('social_security_no')->nullable(true);
            $table->string('tax_file_no')->nullable(true);
            $table->string('nid_no')->nullable(true);
            $table->bigInteger('shirt_size_id')->nullable(true)->unique()->unsigned();
            $table->text('allergies')->nullable(true);
        });
        Schema::create('addresses', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->text('address')->nullable(true);
            $table->string('zip')->nullable(true);
            $table->uuid('country_id')->nullable(true)->unique()->unsigned();
            $table->uuid('people_id')->nullable(true)->unsigned();
            $table->uuid('state_id')->nullable(true)->unique()->unsigned();
            $table->uuid('city_id')->nullable(true)->unique()->unsigned();
        });
        Schema::create('countries', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->string('name')->nullable(true);
            $table->string('country_code')->nullable(true);
            $table->string('lattitude')->nullable(true);
            $table->string('longitude')->nullable(true);
            $table->string('iso_code')->nullable(true);
            $table->string('iso3_code')->nullable(true);
            $table->string('numeric_code')->nullable(true);
            $table->string('capital')->nullable(true);
            $table->string('currency')->nullable(true);
            $table->string('currency_code')->nullable(true);
            $table->string('currency_symbol')->nullable(true);
            $table->string('flag')->nullable(true);
            $table->uuid('created_by');
            $table->uuid('updated_by');
        });
        Schema::create('states', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->string('name')->nullable(true);
            $table->uuid('created_by');
            $table->uuid('updated_by');
            $table->bigInteger('country_id')->nullable(true)->unsigned();
        });
        Schema::create('cities', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->string('name')->nullable(true);
            $table->uuid('created_by');
            $table->uuid('updated_by');
            $table->bigInteger('state_id')->nullable(true)->unsigned();
        });
        Schema::create('social_links', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->uuid('employee_id')->nullable(true);
            $table->string('app_name')->nullable(true);
            $table->string('icon')->nullable(true);
            $table->string('profile_url')->nullable(true);
            $table->uuid('created_by');
            $table->uuid('updated_by');
            $table->uuid('people_id')->nullable(true)->unsigned();
        });
        Schema::create('contacts', function (Blueprint $table) {
            $table->uuid('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->uuid('employee_id')->nullable(true);
            $table->string('email')->nullable(true);
            $table->string('phone')->nullable(true);
            $table->uuid('created_by');
            $table->uuid('updated_by');
            $table->uuid('people_id')->nullable(true)->unsigned();
        });
        Schema::table('people', function (Blueprint $table) {
            $table->foreign('shirt_size_id')->references('id')->on('shirt_sizes');
        });
        Schema::table('addresses', function (Blueprint $table) {
            $table->foreign('country_id')->references('id')->on('countries');
        });
        Schema::table('addresses', function (Blueprint $table) {
            $table->foreign('people_id')->references('id')->on('people');
        });
        Schema::table('addresses', function (Blueprint $table) {
            $table->foreign('state_id')->references('id')->on('states');
        });
        Schema::table('addresses', function (Blueprint $table) {
            $table->foreign('city_id')->references('id')->on('cities');
        });
        Schema::table('states', function (Blueprint $table) {
            $table->foreign('country_id')->references('id')->on('countries');
        });
        Schema::table('cities', function (Blueprint $table) {
            $table->foreign('state_id')->references('id')->on('states');
        });
        Schema::table('social_links', function (Blueprint $table) {
            $table->foreign('people_id')->references('id')->on('people');
        });
        Schema::table('contacts', function (Blueprint $table) {
            $table->foreign('people_id')->references('id')->on('people');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('contacts')) {
            Schema::table('contacts', function (Blueprint $table) {
                $table->dropForeign(['people_id']);
            });
        }
        if (Schema::hasTable('social_links')) {
            Schema::table('social_links', function (Blueprint $table) {
                $table->dropForeign(['people_id']);
            });
        }
        if (Schema::hasTable('cities')) {
            Schema::table('cities', function (Blueprint $table) {
                $table->dropForeign(['state_id']);
            });
        }
        if (Schema::hasTable('states')) {
            Schema::table('states', function (Blueprint $table) {
                $table->dropForeign(['country_id']);
            });
        }
        if (Schema::hasTable('addresses')) {
            Schema::table('addresses', function (Blueprint $table) {
                $table->dropForeign(['city_id']);
            });
        }
        if (Schema::hasTable('addresses')) {
            Schema::table('addresses', function (Blueprint $table) {
                $table->dropForeign(['state_id']);
            });
        }
        if (Schema::hasTable('addresses')) {
            Schema::table('addresses', function (Blueprint $table) {
                $table->dropForeign(['people_id']);
            });
        }
        if (Schema::hasTable('addresses')) {
            Schema::table('addresses', function (Blueprint $table) {
                $table->dropForeign(['country_id']);
            });
        }
        if (Schema::hasTable('people')) {
            Schema::table('people', function (Blueprint $table) {
                $table->dropForeign(['shirt_size_id']);
            });
        }
        Schema::dropIfExists('contacts');
        Schema::dropIfExists('social_links');
        Schema::dropIfExists('cities');
        Schema::dropIfExists('states');
        Schema::dropIfExists('countries');
        Schema::dropIfExists('addresses');
        Schema::dropIfExists('people');
        Schema::dropIfExists('shirt_sizes');
    }
}
