<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractCity
* @package App\Models\AbstractModels
*
* @property string $id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property string $name
* @property string $created_by
* @property string $updated_by
* @property bigInteger $state_id
* @property \App\Models\State|null $state
* @property \App\Models\Address|null $addresses
*/ 
abstract class AbstractCity extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'string';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'name' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string',
        'state_id' => 'integer'
    ];
    
    public function state()
    {
        return $this->belongsTo('\App\Models\State', 'state_id', 'id');
    }
    
    public function addresses()
    {
        return $this->hasOne('\App\Models\Address', 'city_id', 'id');
    }
}
