<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractState
* @package App\Models\AbstractModels
*
* @property string $id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property string $name
* @property string $created_by
* @property string $updated_by
* @property bigInteger $country_id
* @property \App\Models\Country|null $country
* @property \App\Models\Address|null $addresses
* @property \Illuminate\Database\Eloquent\Collection $cities
*/ 
abstract class AbstractState extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'string';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'name' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string',
        'country_id' => 'integer'
    ];
    
    public function country()
    {
        return $this->belongsTo('\App\Models\Country', 'country_id', 'id');
    }
    
    public function addresses()
    {
        return $this->hasOne('\App\Models\Address', 'state_id', 'id');
    }
    
    public function cities()
    {
        return $this->hasMany('\App\Models\City', 'state_id', 'id');
    }
}
