<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractCountry
* @package App\Models\AbstractModels
*
* @property string $id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property string $name
* @property string $country_code
* @property string $lattitude
* @property string $longitude
* @property string $iso_code
* @property string $iso3_code
* @property string $numeric_code
* @property string $capital
* @property string $currency
* @property string $currency_code
* @property string $currency_symbol
* @property string $flag
* @property string $created_by
* @property string $updated_by
* @property \App\Models\Address|null $addresses
* @property \Illuminate\Database\Eloquent\Collection $states
*/ 
abstract class AbstractCountry extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'string';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'name' => 'string',
        'country_code' => 'string',
        'lattitude' => 'string',
        'longitude' => 'string',
        'iso_code' => 'string',
        'iso3_code' => 'string',
        'numeric_code' => 'string',
        'capital' => 'string',
        'currency' => 'string',
        'currency_code' => 'string',
        'currency_symbol' => 'string',
        'flag' => 'string',
        'created_by' => 'string',
        'updated_by' => 'string'
    ];
    
    public function addresses()
    {
        return $this->hasOne('\App\Models\Address', 'country_id', 'id');
    }
    
    public function states()
    {
        return $this->hasMany('\App\Models\State', 'country_id', 'id');
    }
}
