<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractPeople
* @package App\Models\AbstractModels
*
* @property string $id
* @property string $employee_id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property string $status
* @property string $first_name
* @property string $middle_name
* @property string $last_name
* @property string $preferred_name
* @property \Carbon\Carbon $date_of_birth
* @property string $gender
* @property string $marital_status
* @property string $social_security_no
* @property string $tax_file_no
* @property string $nid_no
* @property bigInteger $shirt_size_id
* @property text $allergies
* @property \App\Models\ShirtSize|null $shirtSize
* @property \Illuminate\Database\Eloquent\Collection $addresses
* @property \Illuminate\Database\Eloquent\Collection $socialLinks
* @property \Illuminate\Database\Eloquent\Collection $contacts
*/ 
abstract class AbstractPeople extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'string';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'employee_id' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'status' => 'string',
        'first_name' => 'string',
        'middle_name' => 'string',
        'last_name' => 'string',
        'preferred_name' => 'string',
        'date_of_birth' => 'datetime',
        'gender' => 'string',
        'marital_status' => 'string',
        'social_security_no' => 'string',
        'tax_file_no' => 'string',
        'nid_no' => 'string',
        'shirt_size_id' => 'integer',
        'allergies' => 'string'
    ];
    
    public function shirtSize()
    {
        return $this->belongsTo('\App\Models\ShirtSize', 'shirt_size_id', 'id');
    }
    
    public function addresses()
    {
        return $this->hasMany('\App\Models\Address', 'people_id', 'id');
    }
    
    public function socialLinks()
    {
        return $this->hasMany('\App\Models\SocialLink', 'people_id', 'id');
    }
    
    public function contacts()
    {
        return $this->hasMany('\App\Models\Contact', 'people_id', 'id');
    }
}
