<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractAddress
* @package App\Models\AbstractModels
*
* @property string $id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property text $address
* @property string $zip
* @property string $country_id
* @property string $people_id
* @property string $state_id
* @property string $city_id
* @property \App\Models\Country|null $country
* @property \App\Models\People|null $people
* @property \App\Models\State|null $state
* @property \App\Models\City|null $city
*/ 
abstract class AbstractAddress extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'string';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'address' => 'string',
        'zip' => 'string',
        'country_id' => 'string',
        'people_id' => 'string',
        'state_id' => 'string',
        'city_id' => 'string'
    ];
    
    public function country()
    {
        return $this->belongsTo('\App\Models\Country', 'country_id', 'id');
    }
    
    public function people()
    {
        return $this->belongsTo('\App\Models\People', 'people_id', 'id');
    }
    
    public function state()
    {
        return $this->belongsTo('\App\Models\State', 'state_id', 'id');
    }
    
    public function city()
    {
        return $this->belongsTo('\App\Models\City', 'city_id', 'id');
    }
}
